baseURL: https://hugiselephant.com
languageCode: en-us
title: Hugi's Elephant
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Welcome 🐘
    Content: I'd like to invite you on a thoughtful journey with me. 

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/hugiselephant"
    - name: "youtube"
      url: "https://www.youtube.com/@hugiselephant"
    - name: "twitter"
      url: "https://twitter.com/hugiselephant"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/hugiselephant/"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/hugiselephant"
    - name: "rss"
      url: "https://hugiselephant.github.io/index.xml"

  ShowReadingTime: true
  author: "Sung Hong"
  contact: "sung@hugiselephant.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
